backend:
  name: github
  repo: Opus667/pepaDEVbr
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: "https://pepa.dev.br"

collections:
  - name: "blog"
    label: "Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
  - name: "projects"
    label: "Projects"
    folder: "src/content/projets"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
